export const FILTER_OPTIONS = {
    locations: [
        'Eastern Europe',
        'Middle East',
        'North Africa',
        'Sub-Saharan Africa',
        'South Asia',
        'Southeast Asia',
        'Central Asia',
        'Latin America',
    ],
    categories: [
        'Assault Rifle',
        'Battle Rifle',
        'Pistol',
        'Submachine Gun',
        'Light Machine Gun',
        'Sniper Rifle',
        'Shotgun',
    ],
    sources: ['Telegram', 'Twitter', 'Facebook', 'Reddit', 'News Media', 'OSINT Reports', 'Local Sources'],
    manufacturers: [
        'Kalashnikov Concern',
        'Heckler & Koch',
        'FN Herstal',
        'Glock',
        'Colt',
        'Sig Sauer',
        'Remington',
        'Beretta',
    ],
    calibres: [
        '5.45×39mm',
        '5.56×45mm NATO',
        '7.62×39mm',
        '7.62×51mm NATO',
        '9×19mm Parabellum',
        '4.6×30mm',
        '.338 Lapua Magnum',
        '12 Gauge',
    ],
    operationalStatus: ['Operational', 'Non-operational', 'Modified', 'Damaged', 'Unknown'],
};
