import { WeaponEntry } from './type';

export const SAMPLE_ENTRIES: WeaponEntry[] = [
    {
        id: 1,
        image: 'https://i.redd.it/qf3g91g4xexb1.png',
        title: 'Modified AK-74M identified in conflict zone',
        source: 'Telegram',
        location: 'Eastern Europe',
        timestamp: '10 minutes ago',
        confidence: 'High',
        verified: 'Verified',
        category: 'Assault Rifle',
        calibre: '5.45×39mm',
        manufacturer: 'Kalashnikov Concern',
        countryOfOrigin: 'Russia',
        yearOfManufacture: '2010',
        operationalStatus: 'Operational',
        description:
            'AK-74M with modern attachments including EOTech optic and modified handguard. Serial number visible in high-resolution images.',
        sourceUrl: 'https://example.com/source1',
        sourceDate: '2024-03-13',
        verifiedBy: ['OSINT Team Alpha', 'Weapons Specialist'],
        tags: ['ak-74m', 'modified', 'russian', 'optics', 'serialized'],
        relatedEntries: [2, 5],
    },
    {
        id: 2,
        image: 'https://i.redd.it/qf3g91g4xexb1.png',
        title: 'HK416 rifle configuration analysis',
        source: 'OSINT Reports',
        location: 'Central Europe',
        timestamp: '1 hour ago',
        confidence: 'Low',
        verified: 'Unverified',
        category: 'Assault Rifle',
        calibre: '5.56×45mm NATO',
        manufacturer: 'Heckler & Koch',
        countryOfOrigin: 'Germany',
        yearOfManufacture: '2019',
        operationalStatus: 'Operational',
        description:
            'HK416 with LPVO scope, PEQ-15 laser designator, and Surefire suppressor. Multiple identifying features visible.',
        sourceDate: '2024-03-13',
        sourceUrl: 'https://example.com/source1',
        verifiedBy: ['Military Technical Expert'],
        tags: ['hk416', 'suppressed', 'german', 'nato-spec'],
    },
    {
        id: 3,
        image: 'https://i.redd.it/qf3g91g4xexb1.png',
        title: 'FN SCAR-H Battle Rifle Documentation',
        source: 'Local Sources',
        location: 'Western Asia',
        timestamp: '3 hours ago',
        confidence: 'High',
        verified: 'Verified',
        category: 'Battle Rifle',
        calibre: '7.62×51mm NATO',
        manufacturer: 'FN Herstal',
        countryOfOrigin: 'Belgium',
        yearOfManufacture: '2020',
        operationalStatus: 'Operational',
        description: 'SCAR-H with extended barrel and variable power scope. Markings indicate recent production batch.',
        sourceDate: '2024-03-13',
        sourceUrl: 'https://example.com/source1',
        verifiedBy: ['Regional Security Team'],
        tags: ['scar-h', 'belgian', 'battle-rifle', 'nato-spec'],
    },
    {
        id: 4,
        image: 'https://i.redd.it/qf3g91g4xexb1.png',
        title: 'Glock 19X Analysis',
        source: 'News Media',
        location: 'North America',
        timestamp: '6 hours ago',
        confidence: 'Medium',
        verified: 'Disputed',
        category: 'Pistol',
        calibre: '9×19mm Parabellum',
        manufacturer: 'Glock',
        countryOfOrigin: 'Austria',
        yearOfManufacture: '2021',
        operationalStatus: 'Operational',
        description: 'Standard Glock 19X with factory configuration. Images show distinctive coyote-colored frame.',
        sourceDate: '2024-03-13',
        sourceUrl: 'https://example.com/source1',
        tags: ['glock', 'pistol', '19x', 'standard-config'],
    },
    {
        id: 5,
        image: 'https://i.redd.it/qf3g91g4xexb1.png',
        title: 'MP7A2 PDW Identification',
        source: 'OSINT Reports',
        location: 'Southeast Europe',
        timestamp: '12 hours ago',
        confidence: 'Medium',
        verified: 'Partially Verified',
        category: 'Submachine Gun',
        calibre: '4.6×30mm',
        manufacturer: 'Heckler & Koch',
        countryOfOrigin: 'Germany',
        yearOfManufacture: '2018',
        operationalStatus: 'Operational',
        description: 'MP7A2 Personal Defense Weapon with folding stock and RMR sight. Additional magazines visible.',
        sourceDate: '2024-03-13',
        sourceUrl: 'https://example.com/source1',
        tags: ['mp7', 'pdw', 'german', 'compact'],
    },
    {
        id: 6,
        image: 'https://i.redd.it/qf3g91g4xexb1.png',
        title: 'M24 Sniper Weapon System',
        source: 'Local Sources',
        location: 'Middle East',
        timestamp: '1 day ago',
        confidence: 'High',
        verified: 'Verified',
        category: 'Sniper Rifle',
        calibre: '7.62×51mm NATO',
        manufacturer: 'Remington',
        countryOfOrigin: 'United States',
        yearOfManufacture: '2015',
        operationalStatus: 'Operational',
        description: 'M24 SWS with Leupold Mk4 scope and Harris bipod. Stock shows unit markings.',
        sourceDate: '2024-03-13',
        sourceUrl: 'https://example.com/source1',
        verifiedBy: ['Weapon Systems Analyst'],
        tags: ['m24', 'sniper', 'american', 'precision'],
    },
];
